@baseUrl = http://localhost:8072
@url = {{baseUrl}}/api/v2

@token = eyJraWQiOiIxNTE1NWVlNC1hMzk1LTRiNTItODAxYy1jYTVjMGZhMjliNTEiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJvaWRjLWNsaWVudCIsImF1ZCI6Im9pZGMtY2xpZW50IiwibmJmIjoxNzE3MjM3MjQ1LCJzY29wZSI6WyJtZXNzYWdlLnJlYWQiLCJtZXNzYWdlLndyaXRlIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTAwMCIsImV4cCI6MTcxNzIzNzU0NSwiaWF0IjoxNzE3MjM3MjQ1LCJqdGkiOiIyZjcwMjU5NS1jNjhjLTQwY2QtODQyYS1hZTQxZWJmYmRlZjYifQ.VsVkKaaLq94s5AhE4F2vw5kHgofeMYLr72QBqzXIls5MvFhOxJbs9bGTE1IWKmJ768ksk7y0K7RDl77rC7vtdf8dYusWvcBEb_1rvBpq_AV0y2GVUcZwdvLYwugLwZ0pPGQJKUVNU_YDg6HPiRv2kIab4sNAcdmT8INL4--xXa6Ozm7qqFcwBlCqTyuW6jaahucGj9yh-vW4gBcQ8snOZY2hgkuikUizC1xx3EljZLkpXVGaMoMOVJyRswNdhcxkv_Qi2cndWAfPU_VYMddlS5wPzfyo7d_UL04rezBxYnn78PKtjs5R5fP4pl0UkPyhRWSOiEt_rqd7_HN0lr-IZQ
# actuator health check
GET {{baseUrl}}/actuator/health

###

# actuator kubernetes readiness check
GET {{baseUrl}}/actuator/health/readiness

###

# actuator kubernetes liveness check
GET {{baseUrl}}/actuator/health/liveness

###
GET {{url}}/beers
Authorization: Bearer {{token}}

###

GET {{url}}/beers/0

###

GET {{url}}/beers/1

###

GET {{url}}/beers/4

###

POST {{url}}/beers
Content-Type: application/json

{
    "beerName": "Salvator Bock",
    "beerStyle": "DARK",
    "upc": "12345",
    "price": 6.78,
    "quantityOnHand": 7
}

###

PUT {{url}}/beers/4
Content-Type: application/json

{
  "beerName": "Salvator Bock **UPDATED AGAIN**",
  "beerStyle": "STOUT",
  "upc": "12342",
  "quantityOnHand": 13,
  "price": 11.23
}

###

PUT {{url}}/beers/0
Content-Type: application/json

{
  "beerName": "Salvator Bock **UPDATED AGAIN**",
  "beerStyle": "STOUT",
  "upc": "12342",
  "quantityOnHand": 13,
  "price": 11.23
}

###

PATCH {{url}}/beers/4
Content-Type: application/json

{
  "beerName": "**PATCHED ***"
}

###

PATCH {{url}}/beers/4
Content-Type: application/json

{
  "beerStyle": "DARK"
}

###
DELETE {{url}}/beers/1

###

DELETE {{url}}/beers/0

###

GET {{url}}/customers

###

GET {{url}}/customers/0

###

GET {{url}}/customers/1

###

GET {{url}}/customers/5

###

POST {{url}}/customers
Content-Type: application/json

{
    "name": "Post GbR"
}

###

PUT {{url}}/customers/5
Content-Type: application/json

{
    "name": "Post GbR **UPDATED**"
}

###

PUT {{url}}/customers/0
Content-Type: application/json

{
    "name": "Hamma Ned"
}

###

PATCH {{url}}/customers/5
Content-Type: application/json

{
  "name": "Post GbR **PATCHED **"
}

###

###
DELETE {{url}}/customers/5

###

DELETE {{url}}/customers/0

###
